# Generated by Django 2.0.4 on 2018-06-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone_fixo',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
