# Generated by Django 2.0.4 on 2018-08-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
