# Generated by Django 2.1 on 2018-08-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_auto_20180806_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributo',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='valoratributo',
            options={'verbose_name': 'Valor do Atributo', 'verbose_name_plural': 'Valores dos Atributos'},
        ),
        migrations.AlterUniqueTogether(
            name='documentoatributo',
            unique_together={('tipo', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='valoratributo',
            unique_together={('tipo', 'usuario')},
        ),
    ]
