# Generated by Django 2.0.4 on 2018-08-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_auto_20180827_1937'),
        ('conta', '0003_auto_20180827_1214'),
    ]

    operations = [
    ]
