# Generated by Django 2.0.4 on 2018-06-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_auto_20180620_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
