# Generated by Django 2.1 on 2019-04-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_auto_20180828_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo',
            name='fake_deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atributo',
            name='fake_deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='fake_deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='fake_deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='fake_deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamento',
            name='fake_deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoatributo',
            name='fake_deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentoatributo',
            name='fake_deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fake_deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fake_deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valoratributo',
            name='fake_deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valoratributo',
            name='fake_deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
