# Generated by Django 2.0.4 on 2018-06-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_auto_20180620_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
    ]
