# Generated by Django 2.0.4 on 2018-06-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0005_remove_user_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefone_fixo',
        ),
    ]
