# Generated by Django 2.0.4 on 2018-06-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0006_remove_user_telefone_fixo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
