# Generated by Django 2.0.4 on 2018-07-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0008_auto_20180705_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name']},
        ),
    ]
