# Generated by Django 2.1 on 2019-04-03 18:28

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('android', models.FileField(blank=True, null=True, upload_to=api.models.android_upload_to)),
                ('ios', models.FileField(blank=True, null=True, upload_to=api.models.ios_upload_to)),
                ('major', models.SmallIntegerField()),
                ('minor', models.SmallIntegerField()),
                ('patch', models.SmallIntegerField()),
                ('liberado', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
            ],
            options={
                'ordering': ('-major', '-minor', '-patch'),
            },
        ),
    ]
