# Generated by Django 2.0.4 on 2018-08-24 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import relatorios.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fake_deletado', models.BooleanField(default=False)),
                ('fake_deletado_em', models.DateTimeField(null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('nivel', models.PositiveSmallIntegerField(editable=False)),
                ('nivel_superior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subblocos', to='relatorios.Bloco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fake_deletado', models.BooleanField(default=False)),
                ('fake_deletado_em', models.DateTimeField(null=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editores', to='relatorios.Bloco')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_blocos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fake_deletado', models.BooleanField(default=False)),
                ('fake_deletado_em', models.DateTimeField(null=True)),
                ('imagem', models.ImageField(upload_to=relatorios.models.upload_figura)),
                ('legenda', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fake_deletado', models.BooleanField(default=False)),
                ('fake_deletado_em', models.DateTimeField(null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='figura',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figuras', to='relatorios.Relatorio'),
        ),
        migrations.AddField(
            model_name='figura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloco',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='relatorios.Relatorio'),
        ),
        migrations.AddField(
            model_name='bloco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='editor',
            unique_together={('bloco', 'editor')},
        ),
    ]
