# Generated by Django 2.0.4 on 2018-08-27 15:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='figura',
            managers=[
                ('objetcs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='relatorio',
            managers=[
                ('objetcs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bloco',
            name='descricao',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figura',
            name='descricao',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatorio',
            name='descricao',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
