# Generated by Django 2.1 on 2018-08-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_auto_20180827_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloco',
            options={'ordering': ['criado_em']},
        ),
    ]
