# Generated by Django 2.1 on 2018-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_auto_20180830_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloco',
            name='ordem',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
