# Generated by Django 2.1 on 2018-09-11 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorios', '0004_auto_20180831_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloco',
            name='editor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='editor',
            unique_together={('bloco', 'editor', 'usuario')},
        ),
    ]
