# Generated by Django 2.1 on 2018-09-11 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0005_auto_20180910_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='bloco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editores', to='relatorios.Bloco'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='editor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_blocos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='editor',
            unique_together=set(),
        ),
    ]
