# Generated by Django 2.1 on 2018-09-11 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0007_auto_20180910_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_blocos', to=settings.AUTH_USER_MODEL),
        ),
    ]
