# Generated by Django 2.1 on 2019-04-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0009_auto_20180911_0102'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='figura',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='relatorio',
            managers=[
            ],
        ),
    ]
