# Generated by Django 2.1 on 2019-04-25 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import relatorios.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorios', '0011_auto_20190409_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibtex',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fake_deletado', models.BooleanField(default=False)),
                ('fake_deletado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bibtex',
                'verbose_name_plural': 'Bibtex',
            },
        ),
        migrations.CreateModel(
            name='TemplateLatex',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fake_deletado', models.BooleanField(default=False)),
                ('fake_deletado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateLatexRelatorio',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fake_deletado', models.BooleanField(default=False)),
                ('fake_deletado_em', models.DateTimeField(blank=True, null=True)),
                ('relatorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Relatorio')),
                ('template_blocos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloco_set', to='relatorios.TemplateLatex')),
                ('template_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_set', to='relatorios.TemplateLatex')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
