# Generated by Django 2.1 on 2019-04-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0012_bibtex_templatelatex_templatelatexrelatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatelatex',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='templatelatex',
            name='conteudo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
