# Generated by Django 2.1 on 2019-05-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import relatorios.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorios', '0013_auto_20190425_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fake_deletado', models.BooleanField(default=False)),
                ('fake_deletado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(max_length=255, upload_to=relatorios.models.upload_pdfs)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='relatorios.Relatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
