# Generated by Django 2.1 on 2018-09-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='fake_deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='fake_deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
