# Generated by Django 2.0.4 on 2018-07-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_messages', '0002_auto_20180709_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userthread',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='message',
            name='editado_em',
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
