# Generated by Django 2.1 on 2019-04-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_messages', '0002_auto_20180910_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fake_deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='fake_deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userthread',
            name='fake_deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userthread',
            name='fake_deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
