# Generated by Django 2.0.4 on 2018-07-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_messages', '0004_auto_20180709_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
