# Generated by Django 2.0.4 on 2018-07-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_messages', '0010_message_file_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-sent_at',)},
        ),
    ]
