# Generated by Django 2.0.4 on 2018-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_messages', '0011_auto_20180717_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='data_finalizada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
