# Generated by Django 2.0.4 on 2018-07-30 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questionarios.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoResposta',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to=questionarios.models.caminho_para_arquivos)),
            ],
            options={
                'verbose_name': 'Arquivo Resposta',
                'verbose_name_plural': 'Arquivos Resposta',
            },
        ),
        migrations.CreateModel(
            name='CoordenadaResposta',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Coordenada Resposta',
                'verbose_name_plural': 'Coordenadas Resposta',
            },
        ),
        migrations.CreateModel(
            name='ImagemResposta',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to=questionarios.models.caminho_para_imagens)),
            ],
            options={
                'verbose_name': 'Imagem Resposta',
                'verbose_name_plural': 'Imagens Resposta',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='NumeroResposta',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.FloatField()),
            ],
            options={
                'verbose_name': 'Numero Resposta',
                'verbose_name_plural': 'Numeros Resposta',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variavel', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('tipo', models.PositiveSmallIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ('tipo',),
            },
        ),
        migrations.CreateModel(
            name='PerguntaDoQuestionario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Pergunta do Questionario',
                'verbose_name_plural': 'Perguntas dos Questionarios',
                'ordering': ('questionario', 'ordem', 'pergunta'),
            },
        ),
        migrations.CreateModel(
            name='PossivelEscolha',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Possivel Escolha',
                'verbose_name_plural': 'Possiveis Escolhas',
            },
        ),
        migrations.CreateModel(
            name='PossivelEscolhaResposta',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('possivel_escolha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.PossivelEscolha')),
            ],
            options={
                'verbose_name': 'Possivel Escolha Resposta',
                'verbose_name_plural': 'Possiveis Escolhas Resposta',
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('publicado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Questionario',
                'verbose_name_plural': 'Questionarios',
            },
        ),
        migrations.CreateModel(
            name='RespostaPergunta',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionarios.Localizacao')),
            ],
            options={
                'verbose_name': 'Resposta da Pergunta',
                'verbose_name_plural': 'Respostas das Perguntas',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestionario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionarios.Questionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta Questionario',
                'verbose_name_plural': 'Respostas Questionarios',
            },
        ),
        migrations.CreateModel(
            name='TextoResposta',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('resposta_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='questionarios.RespostaPergunta')),
            ],
            options={
                'verbose_name': 'Texto Resposta',
                'verbose_name_plural': 'Textos Resposta',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ('nome', 'sigla'),
            },
        ),
        migrations.CreateModel(
            name='PerguntaArquivo',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionarios.Pergunta')),
            ],
            options={
                'verbose_name': 'Pergunta Arquivo',
                'verbose_name_plural': 'Perguntas Arquivo',
            },
            bases=('questionarios.pergunta',),
        ),
        migrations.CreateModel(
            name='PerguntaCoordenada',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionarios.Pergunta')),
            ],
            options={
                'verbose_name': 'Pergunta Coordenada',
                'verbose_name_plural': 'Perguntas Coordenada',
            },
            bases=('questionarios.pergunta',),
        ),
        migrations.CreateModel(
            name='PerguntaEscolha',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionarios.Pergunta')),
                ('multipla', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pergunta Escolha',
                'verbose_name_plural': 'Perguntas Escolha',
            },
            bases=('questionarios.pergunta',),
        ),
        migrations.CreateModel(
            name='PerguntaImagem',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionarios.Pergunta')),
            ],
            options={
                'verbose_name': 'Pergunta Imagem',
                'verbose_name_plural': 'Perguntas Imagem',
            },
            bases=('questionarios.pergunta',),
        ),
        migrations.CreateModel(
            name='PerguntaNumero',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionarios.Pergunta')),
                ('maior_que', models.FloatField(blank=True, null=True)),
                ('menor_que', models.FloatField(blank=True, null=True)),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.UnidadeMedida')),
            ],
            options={
                'verbose_name': 'Pergunta Numero',
                'verbose_name_plural': 'Perguntas Numero',
            },
            bases=('questionarios.pergunta',),
        ),
        migrations.CreateModel(
            name='PerguntaTexto',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionarios.Pergunta')),
            ],
            options={
                'verbose_name': 'Pergunta Texto',
                'verbose_name_plural': 'Perguntas Texto',
            },
            bases=('questionarios.pergunta',),
        ),
        migrations.AddField(
            model_name='respostapergunta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.Pergunta'),
        ),
        migrations.AddField(
            model_name='respostapergunta',
            name='resposta_questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='questionarios.RespostaQuestionario'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='perguntas',
            field=models.ManyToManyField(related_name='questionarios', through='questionarios.PerguntaDoQuestionario', to='questionarios.Pergunta'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possivelescolharesposta',
            name='resposta_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolhas', to='questionarios.RespostaPergunta'),
        ),
        migrations.AddField(
            model_name='perguntadoquestionario',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.Pergunta'),
        ),
        migrations.AddField(
            model_name='perguntadoquestionario',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.Questionario'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='possivel_escolha_requisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_requisito_de', to='questionarios.PossivelEscolha'),
        ),
        migrations.AddField(
            model_name='numeroresposta',
            name='resposta_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='questionarios.RespostaPergunta'),
        ),
        migrations.AddField(
            model_name='numeroresposta',
            name='unidade_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.UnidadeMedida'),
        ),
        migrations.AddField(
            model_name='imagemresposta',
            name='resposta_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='questionarios.RespostaPergunta'),
        ),
        migrations.AddField(
            model_name='coordenadaresposta',
            name='coordenada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionarios.Localizacao'),
        ),
        migrations.AddField(
            model_name='coordenadaresposta',
            name='resposta_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='questionarios.RespostaPergunta'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='resposta_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='questionarios.RespostaPergunta'),
        ),
        migrations.AlterUniqueTogether(
            name='respostapergunta',
            unique_together={('resposta_questionario', 'pergunta')},
        ),
        migrations.AlterUniqueTogether(
            name='possivelescolharesposta',
            unique_together={('resposta_pergunta', 'possivel_escolha')},
        ),
        migrations.AddField(
            model_name='possivelescolha',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possiveis_escolhas', to='questionarios.PerguntaEscolha'),
        ),
        migrations.AlterUniqueTogether(
            name='perguntadoquestionario',
            unique_together={('questionario', 'pergunta')},
        ),
        migrations.AlterUniqueTogether(
            name='coordenadaresposta',
            unique_together={('resposta_pergunta', 'coordenada')},
        ),
    ]
