# Generated by Django 2.0.4 on 2018-06-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaNumero',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionarios.Pergunta')),
                ('maior_que', models.FloatField(blank=True, null=True)),
                ('menor_que', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('questionarios.pergunta',),
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ('nome', 'sigla'),
            },
        ),
        migrations.AlterField(
            model_name='numeroresposta',
            name='numero',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='perguntanumero',
            name='unidade_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.UnidadeMedida'),
        ),
        migrations.AddField(
            model_name='numeroresposta',
            name='unidade_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionarios.UnidadeMedida'),
            preserve_default=False,
        ),
    ]
