# Generated by Django 2.0.4 on 2018-08-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionario',
            options={'permissions': (('list_questionario', 'Can list questionario'), ('view_questionario', 'Can view questionario')), 'verbose_name': 'Questionario', 'verbose_name_plural': 'Questionarios'},
        ),
    ]
