# Generated by Django 2.0.4 on 2018-08-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0003_pergunta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='pergunta_requisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_requisito_de', to='questionarios.Pergunta'),
        ),
    ]
