# Generated by Django 2.0.4 on 2018-06-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0003_auto_20180615_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivoresposta',
            options={'verbose_name': 'Arquivo Resposta', 'verbose_name_plural': 'Arquivos Resposta'},
        ),
        migrations.AlterModelOptions(
            name='coordenadaresposta',
            options={'verbose_name': 'Coordenada Resposta', 'verbose_name_plural': 'Coordenadas Resposta'},
        ),
        migrations.AlterModelOptions(
            name='imagemresposta',
            options={'verbose_name': 'Imagem Resposta', 'verbose_name_plural': 'Imagens Resposta'},
        ),
        migrations.AlterModelOptions(
            name='localizacao',
            options={'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações'},
        ),
        migrations.AlterModelOptions(
            name='numeroresposta',
            options={'verbose_name': 'Numero Resposta', 'verbose_name_plural': 'Numeros Resposta'},
        ),
        migrations.AlterModelOptions(
            name='perguntaarquivo',
            options={'verbose_name': 'Pergunta Arquivo', 'verbose_name_plural': 'Perguntas Arquivo'},
        ),
        migrations.AlterModelOptions(
            name='perguntacoordenada',
            options={'verbose_name': 'Pergunta Coordenada', 'verbose_name_plural': 'Perguntas Coordenada'},
        ),
        migrations.AlterModelOptions(
            name='perguntadoquestionario',
            options={'ordering': ('questionario', 'ordem', 'pergunta'), 'verbose_name': 'Pergunta do Questionario', 'verbose_name_plural': 'Perguntas dos Questionarios'},
        ),
        migrations.AlterModelOptions(
            name='perguntaimagem',
            options={'verbose_name': 'Pergunta Imagem', 'verbose_name_plural': 'Perguntas Imagem'},
        ),
        migrations.AlterModelOptions(
            name='perguntamultiplaescolha',
            options={'verbose_name': 'Pergunta Multipla Escolha', 'verbose_name_plural': 'Perguntas Multipla Escolha'},
        ),
        migrations.AlterModelOptions(
            name='perguntanumero',
            options={'verbose_name': 'Pergunta Numero', 'verbose_name_plural': 'Perguntas Numero'},
        ),
        migrations.AlterModelOptions(
            name='perguntatexto',
            options={'verbose_name': 'Pergunta Texto', 'verbose_name_plural': 'Perguntas Texto'},
        ),
        migrations.AlterModelOptions(
            name='perguntaunicaescolha',
            options={'verbose_name': 'Pergunta Unica Escolha', 'verbose_name_plural': 'Perguntas Unica Escolha'},
        ),
        migrations.AlterModelOptions(
            name='possivelescolharesposta',
            options={'verbose_name': 'Possivel Escolha Resposta', 'verbose_name_plural': 'Possiveis Escolhas Resposta'},
        ),
        migrations.AlterModelOptions(
            name='respostapergunta',
            options={'verbose_name': 'Resposta da Pergunta', 'verbose_name_plural': 'Respostas das Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='textoresposta',
            options={'verbose_name': 'Texto Resposta', 'verbose_name_plural': 'Textos Resposta'},
        ),
        migrations.AddField(
            model_name='perguntaunicaescolha',
            name='multipla',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='coordenadaresposta',
            unique_together={('resposta_pergunta', 'coordenada')},
        ),
    ]
