# Generated by Django 2.0.4 on 2018-06-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0004_auto_20180619_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostapergunta',
            name='resposta_questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='questionarios.RespostaQuestionario'),
        ),
    ]
