# Generated by Django 2.1 on 2018-08-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0004_pergunta_pergunta_requisito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionario',
            options={'verbose_name': 'Questionario', 'verbose_name_plural': 'Questionarios'},
        ),
    ]
