# Generated by Django 2.1 on 2018-08-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0005_auto_20180827_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoresposta',
            name='resposta_pergunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo', to='questionarios.RespostaPergunta'),
        ),
        migrations.AlterField(
            model_name='coordenadaresposta',
            name='resposta_pergunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenada', to='questionarios.RespostaPergunta'),
        ),
        migrations.AlterField(
            model_name='imagemresposta',
            name='resposta_pergunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to='questionarios.RespostaPergunta'),
        ),
        migrations.AlterField(
            model_name='numeroresposta',
            name='resposta_pergunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numero', to='questionarios.RespostaPergunta'),
        ),
        migrations.AlterField(
            model_name='textoresposta',
            name='resposta_pergunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='texto', to='questionarios.RespostaPergunta'),
        ),
    ]
