# Generated by Django 2.1 on 2018-09-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0006_auto_20180830_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidademedida',
            name='sigla',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
