# Generated by Django 2.0.4 on 2018-09-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0007_auto_20180914_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='perguntas',
        ),
    ]
