# Generated by Django 2.0.4 on 2018-10-12 17:36

from django.db import migrations, models
import django.db.models.deletion
import questionarios.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0008_remove_questionario_perguntas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorCensitario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('setor_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsetores', to='questionarios.SetorCensitario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='respostaquestionario',
            name='setor_censitario',
            field=models.ForeignKey(default=questionarios.models.default_setor_censitario, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionarios.SetorCensitario'),
        ),
        migrations.AlterUniqueTogether(
            name='respostaquestionario',
            unique_together={('setor_censitario', 'questionario')},
        ),
    ]
