# Generated by Django 2.1 on 2019-04-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0010_auto_20190407_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setorcensitario',
            options={'ordering': ('nome',)},
        ),
    ]
