# Generated by Django 2.1 on 2019-04-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0011_auto_20190409_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaquestionario',
            name='setor_censitario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionarios.SetorCensitario'),
        ),
        migrations.AlterField(
            model_name='setorcensitario',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='respostaquestionario',
            unique_together={('setor_censitario', 'questionario')},
        ),
    ]
