# Generated by Django 2.1 on 2019-05-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0013_auto_20190430_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorcensitario',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
