# Generated by Django 2.1 on 2019-05-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0014_auto_20190513_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorcensitario',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='setorcensitario',
            unique_together={('nome', 'setor_superior')},
        ),
    ]
